  func.cpp
  소스.cpp
c:\users\a10\source\repos\project2\project2\소스.cpp(4): warning C4326: 'main'의 반환 형식이 'int'이어야 하는데 'void'입니다.
  코드를 생성하고 있습니다...
소스.obj : error LNK2019: "public: void __thiscall func<int>::Quiz1(int)" (?Quiz1@?$func@H@@QAEXH@Z) 외부 기호(참조 위치: _main 함수)에서 확인하지 못했습니다.
소스.obj : error LNK2019: "public: void __thiscall func<int>::Quiz2(int,int)" (?Quiz2@?$func@H@@QAEXHH@Z) 외부 기호(참조 위치: _main 함수)에서 확인하지 못했습니다.
소스.obj : error LNK2019: "public: void __thiscall func<int>::Quiz3(int,int,int)" (?Quiz3@?$func@H@@QAEXHHH@Z) 외부 기호(참조 위치: _main 함수)에서 확인하지 못했습니다.
소스.obj : error LNK2019: "public: __thiscall func<int>::func<int>(void)" (??0?$func@H@@QAE@XZ) 외부 기호(참조 위치: _main 함수)에서 확인하지 못했습니다.
소스.obj : error LNK2019: "public: __thiscall func<int>::~func<int>(void)" (??1?$func@H@@QAE@XZ) 외부 기호(참조 위치: _main 함수)에서 확인하지 못했습니다.
C:\Users\A10\source\repos\Project2\Debug\Project2.exe : fatal error LNK1120: 5개의 확인할 수 없는 외부 참조입니다.
